### ISSUE TITLE
[bug] 使用adapter-satori时无法发送动态通知

### ISSUE THREAD

**Issue by ZGLinus** [Akokk0/koishi-plugin-bilibili-notify#12]
环境信息
```
System:
    OS: Linux 4.19 Alpine Linux
    CPU: (4) arm64 Cortex-A55

Binaries:
    Node: 18.17.1
    Yarn: 3.6.2

Koishi:
    Core: 4.17.2
    Console: 5.28.0
```
插件信息
```
adapter-satori: 1.0.15
bilibili-notify: 1.2.2-beta.0
```
报错信息
```
2024-03-22 17:25:54 [W] app Error: cannot create effect on inactive context
                            at ForkScope.assertActive (/koishi/node_modules/@cordisjs/core/lib/index.cjs:323:11)
                            at ForkScope.effect (/koishi/node_modules/@cordisjs/core/lib/index.cjs:326:10)
                            at [cordis.invoke] (/koishi/node_modules/undios/lib/index.cjs:170:28)
                            at applyTraceable (/koishi/node_modules/@cordisjs/core/lib/index.cjs:256:32)
                            at http (/koishi/node_modules/@cordisjs/core/lib/index.cjs:262:12)
                            at Proxy.<anonymous> (/koishi/node_modules/undios/lib/index.cjs:78:36)
                            at SatoriBot.<computed> [as createMessage] (/koishi/node_modules/@satorijs/adapter-satori/lib/index.js:89:22)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async SatoriBot.sendMessage (/koishi/node_modules/@satorijs/core/lib/index.cjs:326:22)
```
其他信息
- 使用其他插件，例如 [bilibili-live-monitor](https://github.com/Slime00/bilibili-live-monitor) 可以正常发送图片

**Comment by ZGLinus** [comment]
在1.2.2-beta.1已修复
