### ISSUE TITLE
更新到最新版本后好像和auth插件有冲突，一直在报错

### ISSUE THREAD

**Issue by assassinliujie** [Akokk0/koishi-plugin-bilibili-notify#16]
app Error: AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY
                            at f.handleError (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:90:53)
                            at f.prepare (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:88:312)
                            at #exec (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:312:28)
                            at #run (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:340:15)
                            at SQLiteDriver.prepare (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:229:16)
                            at Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:810:18)
                            at async Promise.all (index 5)
                            at async Proxy.prepared (/koishi/node_modules/minato/lib/index.cjs:788:5)
                            at async Executable.execute (/koishi/node_modules/minato/lib/index.cjs:429:5)
                            at async Proxy.upsert (/koishi/node_modules/minato/lib/index.cjs:987:12)
2024-04-26 02:28:26 [I] sqlite auto migrating table loginBili

**Comment by Akokk0** [comment]
更新使用的数据库插件应该可以解决问题
