### ISSUE TITLE
与PostgreSQL不兼容

### ISSUE THREAD

**Issue by CDN18** [Akokk0/koishi-plugin-bilibili-notify#7]
使用PostgreSQL提供数据库服务时，登录后会无法储存refresh token，进而报错“二维码已失效，请重新登录”

```
2024-03-05 10:45:02 [I] commandRegister 调用bili login指令
2024-03-05 10:45:11 [W] postgres > INSERT INTO "loginBili" ("id", "bili_cookies", "bili_refresh_token") VALUES (1, '***', '***') ON CONFLICT ("id") DO UPDATE SET "bili_cookies" = CASE WHEN ("loginBili"."id" = 1) THEN (excluded."bili_cookies") END, "bili_refresh_token" = CASE WHEN ("loginBili"."id" = 1) THEN (excluded."bili_refresh_token") END, _pg_mtime = 437659318027779 RETURNING _pg_mtime as rtime
2024-03-05 10:45:11 [W] app PostgresError: value too long for type character varying(255)
                            at ErrorResponse (/koishi/node_modules/postgres/cjs/src/connection.js:790:26)
                            at handle (/koishi/node_modules/postgres/cjs/src/connection.js:476:6)
                            at Socket.data (/koishi/node_modules/postgres/cjs/src/connection.js:315:9)
                            at Socket.emit (node:events:518:28)
                            at addChunk (node:internal/streams/readable:559:12)
                            at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
                            at Readable.push (node:internal/streams/readable:390:5)
                            at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
                            at new Query (/koishi/node_modules/postgres/cjs/src/query.js:35:9)
                            at Function.unsafe (/koishi/node_modules/postgres/cjs/src/index.js:121:21)
                            at PostgresDriver.query (/koishi/node_modules/@minatojs/driver-postgres/lib/index.js:480:50)
                            at PostgresDriver.upsert (/koishi/node_modules/@minatojs/driver-postgres/lib/index.js:733:31)
                            at Executable.execute (/koishi/node_modules/minato/lib/index.cjs:296:34)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Proxy.upsert (/koishi/node_modules/minato/lib/index.cjs:680:12)
                            at async Timeout._onTimeout (/koishi/node_modules/koishi-plugin-bilibili-notify/lib/comRegister.js:205:25)
```

**Comment by Akokk0** [comment]
`1.2.0-alpha.5`尝试修复了下

**Comment by CDN18** [comment]
更新后可以正常登录了，感谢修复❤️
